### ISSUE TITLE
Blank lines in FASTAs

### ISSUE THREAD

**Issue by CorinYeatsCGPS** [klebgenomics/Kleborate#86]
A blank line in a FASTA file causes the following error:
```
strain  species N50     ST      virulence_score resistance_score        num_resistance_classes  num_resistance_genes
Traceback (most recent call last):
  File "/usr/local/bin/kleborate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kleborate/__main__.py", line 154, in main
    module_results = modules[module].get_results(unzipped_assembly, minimap2_index, args, results)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kleborate/modules/klebsiella_pneumo_complex__amr/klebsiella_pneumo_complex__amr.py", line 85, in get_results
    res_hits = resminimap_assembly(
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kleborate/shared/resMinimap.py", line 42, in resminimap_assembly
    check_omp_genes(hits_dict, assembly, omp, min_identity, 90.0)
  File "/usr/local/lib/python3.11/site-packages/kleborate/modules/klebsiella_pneumo_complex__amr/omp_mutations.py", line 47, in check_omp_genes
    alignments = aligner.align(query_seq , assembly_seq)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/Bio/Align/__init__.py", line 3960, in align
    score, paths = super().align(sA, sB, strand)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Though rare they are technically valid FASTAs.

**Comment by CorinYeatsCGPS** [comment]
Sorry, I got this wrong, it's actually a duplicate of this issue: https://github.com/klebgenomics/Kleborate/issues/64, so I'll close it.
