### ISSUE TITLE
No module named 'kaptive.misc'

### ISSUE THREAD

**Issue by erinyoung** [klebgenomics/Kleborate#88]
I have minimap2 and mash in my environment, so I thought I could install kleborate with pip (`pip install kleborate`). To me, it was kind of like https://kleborate.readthedocs.io/en/latest/Installation.html, without the conda environment. 

Everything seemed to install fine, but when I tried to run `--help`, I was given the following error.

```
$ kleborate --help
Traceback (most recent call last):
  File "/opt/conda/bin/kleborate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/kleborate/__main__.py", line 86, in main
    all_module_names, modules = import_modules()
                                ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/site-packages/kleborate/__main__.py", line 374, in import_modules
    modules[m] = importlib.import_module(f'..modules.{m}.{m}', __name__)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/conda/lib/python3.12/site-packages/kleborate/modules/klebsiella_pneumo_complex__kaptive/klebsiella_pneumo_complex__kaptive.py", line 24, in <module>
    from kaptive.misc import check_python_version, check_programs, get_logo, check_cpus, check_file
ModuleNotFoundError: No module named 'kaptive.misc'
```

It looks like kaptive installed just fine, though
```
$ kaptive --help
usage: kaptive <command>

  _  __    _    ____ _____ _____     _______ 
 | |/ /   / \  |  _ \_   _|_ _\ \   / / ____|
 | ' /   / _ \ | |_) || |  | | \ \ / /|  _|  
 | . \  / ___ \|  __/ | |  | |  \ V / | |___ 
 |_|\_\/_/   \_\_|    |_| |___|  \_/  |_____|                                   

            In silico serotyping           

Command:
  
    assembly       In silico serotyping of assemblies
    extract        Extract entries from a Kaptive database
    convert        Convert Kaptive results into different formats

Other options:

  -V, --verbose    Print debug messages to stderr
  -v , --version   Show version number and exit
  -h , --help      Show this help message and exit

For more help, visit: https://kaptive.readthedocs.io/en/latest/
```

**Comment by LeahRoberts** [comment]
It looks like there was an update to Kaptive 2 days ago, what version of Kaptive are you running? 
I downgraded Kaptive to 3.0.0b5 and it seems to work. Might work as a quick fix :)

**Comment by erinyoung** [comment]
Thank you!!!

I installed the latest version today, and it looks like it worked great.
